name: pwa
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1+1

environment:
   sdk: '>=3.1.0-22.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  go_router: ^7.0.1
  image_picker: ^0.8.7+5
  file_picker: ^5.3.2
  flutter_rating_bar: ^4.0.1
  quantity_input: ^1.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - images
